import 'dart:convert';
import 'dart:io';

Map<String, dynamic> readSchema(File file) {
  final data = jsonDecode(file.readAsStringSync());
  if (data is! Map<String, dynamic>) {
    throw StateError('Invalid schema root. Expected JSON object.');
  }
  return data;
}

Map<String, String> stringMap(Map<String, dynamic> root, String key) {
  final value = root[key];
  if (value is! Map<String, dynamic>) {
    throw StateError('Schema key "$key" must be an object.');
  }
  return value.map((k, v) => MapEntry(k, v.toString()));
}

String capitalize(String s) =>
    s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);

String emitSwift(Map<String, dynamic> schema) {
  final channelName = schema['channelName'].toString();
  final methods = stringMap(schema, 'methods');
  final args = stringMap(schema, 'args');
  final states = stringMap(schema, 'states');
  final viewTypes = stringMap(schema, 'viewTypes');

  final b = StringBuffer();
  b.writeln('// Generated by tool/generate_channel_contracts.dart.');
  b.writeln(
    '// Do not edit manually. Update tool/channel_contract.json and regenerate.',
  );
  b.writeln('enum FrdpChannel {');
  b.writeln('  static let name = "$channelName"');
  b.writeln();

  b.writeln('  enum Method {');
  for (final e in methods.entries) {
    b.writeln('    static let ${e.key} = "${e.value}"');
  }
  b.writeln('  }');
  b.writeln();

  b.writeln('  enum Arg {');
  for (final e in args.entries) {
    b.writeln('    static let ${e.key} = "${e.value}"');
  }
  b.writeln('  }');
  b.writeln();

  b.writeln('  enum State {');
  for (final e in states.entries) {
    b.writeln('    static let ${e.key} = "${e.value}"');
  }
  b.writeln('  }');
  b.writeln();

  b.writeln('  enum ViewType {');
  for (final e in viewTypes.entries) {
    b.writeln('    static let ${e.key} = "${e.value}"');
  }
  b.writeln('  }');
  b.writeln('}');

  return b.toString();
}

String emitDart(Map<String, dynamic> schema) {
  final channelName = schema['channelName'].toString();
  final methods = stringMap(schema, 'methods');
  final args = stringMap(schema, 'args');
  final states = stringMap(schema, 'states');

  final b = StringBuffer();
  b.writeln('// Generated by tool/generate_channel_contracts.dart.');
  b.writeln(
    '// Do not edit manually. Update tool/channel_contract.json and regenerate.',
  );
  b.writeln('const String kFrdpChannelName = "$channelName";');
  b.writeln();

  for (final e in methods.entries) {
    b.writeln('const String k${capitalize(e.key)}Method = "${e.value}";');
  }
  b.writeln();

  for (final e in args.entries) {
    b.writeln('const String k${capitalize(e.key)}Arg = "${e.value}";');
  }
  b.writeln();

  for (final e in states.entries) {
    b.writeln('const String k${capitalize(e.key)}State = "${e.value}";');
  }

  return b.toString();
}

void writeFile(String path, String content) {
  final file = File(path);
  file.writeAsStringSync(content);
}

void main() {
  final repoRoot = Directory.current.path;
  final schemaPath = '$repoRoot/tool/channel_contract.json';
  final swiftPath = '$repoRoot/macos/Classes/plugin/FrdpChannelContract.swift';
  final dartPath = '$repoRoot/lib/src/channel/frdp_channel_contract.dart';

  final schema = readSchema(File(schemaPath));
  writeFile(swiftPath, emitSwift(schema));
  writeFile(dartPath, emitDart(schema));

  stdout.writeln('Generated:');
  stdout.writeln(' - $swiftPath');
  stdout.writeln(' - $dartPath');
}
