// Generated by tool/generate_channel_contracts.dart.
// Do not edit manually. Update tool/channel_contract.json and regenerate.
const String kFrdpChannelName = "frdp";

const String kGetPlatformVersionMethod = "getPlatformVersion";
const String kConnectMethod = "connect";
const String kDisconnectMethod = "disconnect";
const String kGetConnectionStateMethod = "getConnectionState";
const String kSendPointerEventMethod = "sendPointerEvent";
const String kSendKeyEventMethod = "sendKeyEvent";
const String kSendClipboardTextMethod = "sendClipboardText";

const String kSessionIdArg = "sessionId";
const String kStateArg = "state";
const String kHostArg = "host";
const String kPortArg = "port";
const String kUsernameArg = "username";
const String kPasswordArg = "password";
const String kDomainArg = "domain";
const String kIgnoreCertificateArg = "ignoreCertificate";
const String kEnableClipboardArg = "enableClipboard";
const String kRenderingBackendArg = "renderingBackend";
const String kPerformanceProfileArg = "performanceProfile";
const String kConnectTimeoutMsArg = "connectTimeoutMs";
const String kXArg = "x";
const String kYArg = "y";
const String kButtonsArg = "buttons";
const String kKeyCodeArg = "keyCode";
const String kIsDownArg = "isDown";
const String kCustomDesktopWidthArg = "customDesktopWidth";
const String kCustomDesktopHeightArg = "customDesktopHeight";
const String kCustomConnectionTypeArg = "customConnectionType";
const String kCustomColorDepthArg = "customColorDepth";
const String kCustomDisableWallpaperArg = "customDisableWallpaper";
const String kCustomDisableFullWindowDragArg = "customDisableFullWindowDrag";
const String kCustomDisableMenuAnimationsArg = "customDisableMenuAnimations";
const String kCustomDisableThemesArg = "customDisableThemes";
const String kCustomAllowDesktopCompositionArg = "customAllowDesktopComposition";
const String kCustomAllowFontSmoothingArg = "customAllowFontSmoothing";
const String kCustomGfxSurfaceCommandsEnabledArg = "customGfxSurfaceCommandsEnabled";
const String kCustomGfxProgressiveArg = "customGfxProgressive";
const String kCustomGfxProgressiveV2Arg = "customGfxProgressiveV2";
const String kCustomGfxPlanarArg = "customGfxPlanar";
const String kCustomGfxH264Arg = "customGfxH264";
const String kCustomGfxAvc444Arg = "customGfxAvc444";
const String kCustomGfxAvc444V2Arg = "customGfxAvc444V2";
const String kClipboardTextArg = "clipboardText";

const String kClipboardEventsEvent = "frdp/clipboard/events";

const String kDisconnectedState = "disconnected";
const String kConnectingState = "connecting";
const String kConnectedState = "connected";
const String kErrorState = "error";
