// Generated by tool/generate_channel_contracts.dart.
// Do not edit manually. Update tool/channel_contract.json and regenerate.
enum FrdpChannel {
  static let name = "frdp"

  enum Method {
    static let getPlatformVersion = "getPlatformVersion"
    static let connect = "connect"
    static let disconnect = "disconnect"
    static let getConnectionState = "getConnectionState"
    static let sendPointerEvent = "sendPointerEvent"
    static let sendKeyEvent = "sendKeyEvent"
    static let sendClipboardText = "sendClipboardText"
  }

  enum Arg {
    static let sessionId = "sessionId"
    static let state = "state"
    static let host = "host"
    static let port = "port"
    static let username = "username"
    static let password = "password"
    static let domain = "domain"
    static let ignoreCertificate = "ignoreCertificate"
    static let renderingBackend = "renderingBackend"
    static let performanceProfile = "performanceProfile"
    static let connectTimeoutMs = "connectTimeoutMs"
    static let x = "x"
    static let y = "y"
    static let buttons = "buttons"
    static let keyCode = "keyCode"
    static let isDown = "isDown"
    static let customDesktopWidth = "customDesktopWidth"
    static let customDesktopHeight = "customDesktopHeight"
    static let customConnectionType = "customConnectionType"
    static let customColorDepth = "customColorDepth"
    static let customDisableWallpaper = "customDisableWallpaper"
    static let customDisableFullWindowDrag = "customDisableFullWindowDrag"
    static let customDisableMenuAnimations = "customDisableMenuAnimations"
    static let customDisableThemes = "customDisableThemes"
    static let customAllowDesktopComposition = "customAllowDesktopComposition"
    static let customAllowFontSmoothing = "customAllowFontSmoothing"
    static let customGfxSurfaceCommandsEnabled = "customGfxSurfaceCommandsEnabled"
    static let customGfxProgressive = "customGfxProgressive"
    static let customGfxProgressiveV2 = "customGfxProgressiveV2"
    static let customGfxPlanar = "customGfxPlanar"
    static let customGfxH264 = "customGfxH264"
    static let customGfxAvc444 = "customGfxAvc444"
    static let customGfxAvc444V2 = "customGfxAvc444V2"
    static let clipboardText = "clipboardText"
  }

  enum Event {
    static let clipboardEvents = "frdp/clipboard/events"
  }

  enum State {
    static let disconnected = "disconnected"
    static let connecting = "connecting"
    static let connected = "connected"
    static let error = "error"
  }

  enum ViewType {
    static let rdpView = "frdp/view"
  }
}
